name: Docker

on:
  push:
    branches:
      - master
jobs:
  check-new-idena-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Hub README & description sync
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: idenadev
          pass: ${{ secrets.DOCKERIO_PASSWORD }}
          slug: idenadev/idena
          readme: ./README.md
          description: true
